### ISSUE TITLE
Update to "Sober Resources" page

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#26]
Add link to District 10 website meetings https://www.aaloudoundistrict10.org/meetings - Erich had added a brief description of each intergroup so was thinking we could add this for D10 : "Loudoun District 10 of Virginia is located in beautiful Loudoun County, Virginia, about 20 minutes west of Dulles Airport and 30 minutes east of Winchester, VA. This website offers information about Alcoholics Anonymous in the Loudoun County, VA area."

**Comment by TheBlueDog** [comment]
Content added
