### ISSUE TITLE
Middle section of the homepage

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#27]
“In the Fall of 1996 the GSRs from Loudoun District 10 were shooting the breeze during or after a District meeting. Meetings at the time were held at The Barn, in Hamilton. We were a small district in terms of number of meetings. I don’t think there were more than a dozen meetings in the District with a GSR.

We got to talking about a district sponsored event that could take place in late Winter that was a sort of celebration of emerging from the Winter doldrums. The idea of having a day long event with simultaneous meetings was taken from a similar event held annually in Mercer County, New Jersey. The first GSRs who planned the first Day of Sharing were Mike S., Pat J., Andy C., Red Hough (now since passed), George B., (passed away) Jim F. Sam G., and Mike E. , and several others whom we could not recall. Others who helped were Oscar and Joe.

Mike S. was able to obtain use of Crossroads UMC for the first event, and they have been our gracious hosts ever since. Mike S. went on a tour of every meeting in the Where and When in our District and invited speakers to host a slate of meetings. Pat J. handled the six-foot subs, and everyone else got volunteers to bring other food and beverages. We wanted to make it a free will offering event with no set entrance fee, so that anyone could attend regardless of ability to pay. And a Free Lunch was key. If you feed them they will come. The Ashburn Country Group were a huge support for the success of the event, contributing lots of manpower and setup and cleanup help.

The first Day of Sharing was very successful. We had just two or three six-foot subs, but the event grew in size every year and eventually grew to the present size. Every year the planning committee seems to have improved upon the previous year by adding their own touch.”  

- Jim F.

**Comment by TheBlueDog** [comment]
This has been added to the next build
