### ISSUE TITLE
Bottom Right Section on the Homepage (Next to the Photo)

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#28]
“It (The Day of Sharing) really has changed since it started. There were fewer meetings and they were more spread out. (Monday night was Ashburn and Tuesday was Lucketts).....the founder was new and thought it was a way to get everyone together and have a sampling of the different meetings. There were boxes of donuts in the am and subs at lunch....it has grown and changed but has always been a great day. I have only missed one year. I was on a Florida trip with my sober ladies so I didn’t cry.”

-Mary Ellen M.

**Comment by TheBlueDog** [comment]
This has been added to the home page
