### ISSUE TITLE
Slide show...?

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#29]
Is it possible to add a "slide show" or carousel somewhere on the main page? If so, I put together a couple graphics to use (attached in 16:9, pls scale down as necessary).
![Serenity Prayer](https://user-images.githubusercontent.com/77367435/104689724-05c6cb80-56d1-11eb-8f59-71752220b02d.png)
![Responsibility Statement](https://user-images.githubusercontent.com/77367435/104689759-18d99b80-56d1-11eb-9b36-0a60368e05be.png)
![ODAAT](https://user-images.githubusercontent.com/77367435/104689854-4de5ee00-56d1-11eb-897f-a373d868bb4d.png)

**Comment by TheBlueDog** [comment]
Slide show has been added to home page
