### ISSUE TITLE
Meeting Schedule

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#36]
8:30 - 9:00 am - Add "Welcome & Announcements"

9 - 10 Block
Under "Start The Week Off Right"
Add "Step 1"

10:15 - 11:15 am
Under "Not A Glum Lot"
Add "Searching and Fearless"

Under "Corrections"
Add "Carrying the message of AA into the Loudoun County Jail"

Under "Ashburn Country Group"
Add "Step 2: Gaining Access to The Higher Power"

Under BYOL
Add "Gratitude"

Under Luckett's Group
Add "The AA Promises"

1:15 - 2:15 block
Next to "Ashburn Women's Group" Add "Women Only"
Add "Out of Isolation and Into Fellowship" 

Under "Sanity Seekers"
Add “Lessons not learned will be repeated”

Under "No Rules"
Add "Step 1"

Under "We Are Here Group"
Add "Steps 6 & 7"

Under 2:30 - 4 pm
Raffle, Sobriety Countdown, Special Guest Speaker Marti R from Buda, TX

**Comment by TheBlueDog** [comment]
Schedule updated in latest build
