### ISSUE TITLE
Schedule Updates

### ISSUE THREAD

**Issue by JF0920** [TheBlueDog/d10-day-of-sharing#39]
8:30 - 9:00 Block
Add "Room Will Remain Open Throughout the Day"
Add: Zoom ID 747 082 2753

9-10 Block:
Catoctin 
Add: Zoom ID 878 349 1805

Start The Week Off Right
Add: Zoom ID:968 957 3156

10:15 Block:
Pine Grove
Add: Zoom ID 878 349 1805

Drive In
Add: Zoom ID 968 957 3156

Not A Glum Lot
Add:  Zoom ID 434 352 8611

Lovettsville
Add: Zoom ID 949 917 9485

Corrections
Add: Zoom ID 279 238 1733

11:30 Block:
Ashburn Country Group
Add: Zoom ID  878 349 1805

BYOL
Add: Zoom ID  968 957 3156

Luckett's Group
Add: Zoom ID  434 352 8611

Leesburg Group
Add Topic "One Day At A Time"
Add: Zoom ID  949 917 9485

Traditions / Concepts
Add: Zoom ID 279 238 1733

1:15 Block:
Ashburn Women's Group - Women's Meeting
Add:  Zoom ID 878 349 1825

Sanity Seekers
Add: Zoom ID 968 957 3156

No Rules
Add:  Zoom ID 434 352 8611

As Bill Sees It
Add: Zoom ID 949 917 9485

We Are Here Group
Add: Zoom ID 279 238 1733

2:30 Block
Add: Zoom ID 747 082 2753

**Comment by TheBlueDog** [comment]
I'll get these added

**Comment by TheBlueDog** [comment]
Updates have been completed.
